### ISSUE TITLE
[Umbrella Issue] Re-document communication methods on the website

### ISSUE THREAD

**Issue by celestehorgan** [inclusivenaming/website#36]
- [x] Add a page to website for workstreams 
- [x] Add/link? public calendar from website 
- [x] Add link to Slack inviter
- [x] Document workstream mailing lists somehow

I'm sure there's things I'm missing cc: @justaugustus, @edwarnicke  – any other thoughts?

**Comment by gkarthiks** [comment]
@celestehorgan the slack inviter is added already right? https://communityinviter.com/apps/inclusive-naming/invite
